name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          OSS_BUCKET: ${{ secrets.OSS_BUCKET}}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID}}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET}}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT}}
        run: |
          pip install -r requirements.txt

          echo 'Pull dataset with DVC'
          dvc pull data -r aliyun_oss

          echo 'Use DVC metrics diff to compare metrics to cml_with_dvc'
          git fetch --prune --unshallow
          dvc metrics diff --show-md cml_with_dvc >> report.md

          echo 'Add figure to report'
          dvc plots diff --target loss.csv --show-vega cml_with_dvc > vega.json
          vl2png vega.json -s 1.3 > vega.png
          echo '![](./vega.png)' >> report.md
          cml comment create --target=pr/cml_with_dvc --publish report.md
